apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: custom-alerts
  namespace: monitoring
  labels:
    release: monitoring

spec:
  groups:

  - name: custom

    rules:

    - alert: HighCPU

      expr: node_cpu_seconds_total > 80

      for: 5m
